# APPLICATION
spring.application.name=backend

# MANAGEMENT ENDPOINT
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# SERVER
server.port=${SERVER_PORT:8080}

# JPA BASE
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# FILE UPLOAD
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB