spring.config.activate.on-profile=dev

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5433/servio_db
spring.datasource.username=servio
spring.datasource.password=servio123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CACHE
spring.data.redis.host=localhost
spring.data.redis.port=6379

# MAIL
mail.host=localhost
mail.port=1025
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
mail.default-sender=no-reply@servio.com

# OBJECT STORAGE
object-storage.endpoint=http://localhost:9000
object-storage.access-key=servio
object-storage.secret-key=servio123
object-storage.bucket=servio-assets

# JWT
application.security.jwt.secret-key=971c2d5a2fc37a983899194f4f997e79a255ab9a18afd593f8f5aa45c7f3306b
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Frontend
app.frontend-url=http://localhost:3001

# Image upload
image.upload.max-size-bytes=2097152
image.upload.allowed-types=image/jpeg,image/png,image/webp

# Identity
identity.user.logo.folder=logos

# DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true